ad_bot/urls.py
from django.urls import path
from .views import IndexView, SettingsView, SwitchView, ReportsView, UpdateData

app_name = 'ad_bot'
urlpatterns = [
    path('index', IndexView.as_view(), name='index'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('switch/', SwitchView.as_view(), name='switch'),
    path('reports/', ReportsView.as_view(), name='reports'),
    path('update/', UpdateData.as_view(), name='update'),
]

botbtc/urls.py
from django.contrib import admin
from django.urls import path, reverse
from django.conf.urls import include
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', RedirectView.as_view(pattern_name='ad_bot:index')),

    path('ad_bot/', include('ad_bot.urls')),
    path('profiles/', include('profiles.urls')),
]

admin.site.site_header = 'LocalBitcoins_bot Administration'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

profiles/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import ProfileSignUp, ProfilePasswordResetView, activate
from django.views import generic


app_name = 'profiles'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', ProfilePasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('signup/', ProfileSignUp.as_view(), name='signup'),

    path('account_activation_sent/', generic.TemplateView.as_view(template_name='registration/account_activation_email_sent.html'), name='account_activation_sent'),
    path('activate/<uidb64>/<token>/', activate, name='activate')
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <title>{% block title %}{% endblock %}</title>    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block custom_css %}
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% endblock %}
  </head>
  <body {% block body_tag %}{% endblock %}>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% block nav_baractive_index %}{% endblock %} dropdown">
	    <a class="nav-link" href="{% url 'ad_bot:index' %}">Статус</a>
          </li>
	  <li class="nav-item {% block nav_baractive_admin %}{% endblock %}">
            <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Админка</a>
	  </li>
	  <li class="nav-item {% block nav_baractive_reports %}{% endblock %}">
            <a class="nav-link" href="{% url 'ad_bot:reports' %}">Отчеты</a>
	  </li>
        </ul>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ad_bot:index' %}">Пользователь: {{ user.get_username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profiles:logout' %}">Выйти</a>
          </li>          
          {% else %}
          <li class="nav-item {% block nav_baractive_login %}{% endblock %}">
		  <a class="nav-link" href="{% url 'profiles:login'%}?next={% url 'ad_bot:index' %}">Залогиниться</a>
          </li>
          <li class="nav-item {% block nav_baractive_register %}{% endblock %}">
            <a class="nav-link" href="{% url 'profiles:signup' %}">Зарегистрироваться</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Bot status{% endblock %}


{% block nav_baractive_index %}active{% endblock %}


{% block content %}
    <div class="starter-template">
    
        <h1 class="bold reddish"><b>Program</b></h1>
        <p>Курс RacBursa по обучению программированию на Python & Django</p>

        {% if messages %}
        <div class="alert alert-success" role="alert">
            <ul class="messages ">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
{% endblock %}