ad_bot/urls.py
from django.urls import path
from .views import IndexView, SettingsView, SwitchView, ReportsView, UpdateData

app_name = 'ad_bot'
urlpatterns = [
    path('index', IndexView.as_view(), name='index'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('switch/', SwitchView.as_view(), name='switch'),
    path('reports/', ReportsView.as_view(), name='reports'),
    path('update/', UpdateData.as_view(), name='update'),
]

botbtc/urls.py
from django.contrib import admin
from django.urls import path, reverse
from django.conf.urls import include
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', RedirectView.as_view(pattern_name='ad_bot:index')),

    path('ad_bot/', include('ad_bot.urls')),
    path('profiles/', include('profiles.urls')),
]

admin.site.site_header = 'LocalBitcoins_bot Administration'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ad_bot/models.py
from django.db import models
from profiles.models import APIKey, Profile
from botbtc import hmac_auth
import json
import requests
from decimal import *


class AdBot(models.Model):
    name = models.CharField(max_length=64, unique=True)
    api_keys = models.ForeignKey('profiles.APIKey',
                                 on_delete=models.CASCADE)
    stop_price = models.DecimalField(max_digits=9,
                                     decimal_places=2,
                                     help_text='Цена для остановки')
    step = models.IntegerField(help_text='Шаг обновления цены')
    volume_max = models.IntegerField(null=True,
                                     help_text='Фильтр по мелким игрокам')
    volume_min = models.IntegerField(null=True,
                                     help_text='Фильтр по крупным игрокам')
    switch = models.BooleanField(default=False)
    frequency = models.DurationField(help_text='Частота обновления')
    payment_method = models.CharField(
        max_length=64,
        choices=(('qiwi', 'QIWI'),
                 ('cash-deposit', 'CASH_DEPOSIT'),
                 ('transfers-with-specific-bank', 'SPECIFIC_BANK'),
                 ('yandex-money', 'YANDEXMONEY')))
    trade_direction = models.CharField(max_length=64,
                                       choices=(('buy-bitcoins-online',
                                                 'ONLINE_SELL'),
                                                ('sell-bitcoins-online',
                                                 'ONLINE_BUY')
                                                ))
    ad_id = models.IntegerField(unique=True)
    username = models.ForeignKey('profiles.Profile',
                                 on_delete=models.CASCADE)
    price_round = models.BooleanField(default=True)
    page_number = models.IntegerField(default=1)
    greetings_text = models.TextField(blank=True, null=True)
    farewell_text = models.TextField(blank=True, null=True)
    enable_autoposting = models.BooleanField(default=False)


    def __str__(self):
        return '%s, %s' % (self.name, self.ad_id)

    def api_connector_init(self):
        self.auth = hmac_auth.hmac(self.api_keys.api_key,
                                   self.api_keys.api_secret)
        self.base_url = 'https://localbitcoins.com'
        self.endpoints = {
                'get_my_ad': '/api/ad-get/%d/' % (self.ad_id),
                'post_upd_equat': '/api/ad-equation/%d/' %
                                                (self.ad_id),
                'public_ads': '/%s/rub/%s/.json?page=%d' %
                                        (self.trade_direction,
                                         self.payment_method,
                                         self.page_number),
                'open_trades': '/api/dashboard/',
                'current_trade': '/api/contact_info/',
                'post_message': '/api/contact_message_post/',
                'released_trades': '/api/dashboard/released/',
                'all_notifications': '/api/notifications/',
                'mark_notification': '/api/notifications/mark_as_read/',
                        }

    def _get_ads(self):
        self.my_ad = self.auth.call('GET', self.endpoints['get_my_ad']).json()
        self.all_ads = requests.get(
                            self.base_url +
                            self.endpoints['public_ads']).json()

    def _get_open_trades(self):
        self.opened_trades = self.auth.call(
                    'GET', self.endpoints['open_trades']).json()

    def _get_released_trades(self, next_p=''):
        self.released_trades = self.auth.call(
                    'GET',
                    self.endpoints['released_trades'],
                    params=next_p).json()

    def _get_curr_trade(self, con_id):
        self.curr_trade = self.auth.call(
                    'GET', self.endpoints['current_trade']+str(con_id)+'/').json()

    def _get_all_notifications(self):
        self.all_notif = self.auth.call(
                    'GET', self.endpoints['all_notifications']).json()

    def _stop_check(self, curr_ad):
        stop_check = True
        temp_price = curr_ad['data']['temp_price']

        if self.trade_direction == 'buy-bitcoins-online':
            if Decimal(float(temp_price)) < self.stop_price:
                stop_check = False
        else:
            if Decimal(float(temp_price)) > self.stop_price:
                stop_check = False
        return stop_check

    def _min_check(self, curr_ad):
        min_check = True
        min_amount = curr_ad['data']['min_amount']
        if min_amount == None:
            min_amount = 0

        if self.volume_min:
            if int(min_amount) > self.volume_min:
                min_check = False
        return min_check

    def _max_check(self, curr_ad):
        max_check = True
        max_amount = curr_ad['data']['max_amount']

        if self.volume_max:
            if int(max_amount) <= self.volume_max:
                max_check = False
        return max_check

    def _filter_check(self, curr_ad):
        result = None
        if self._max_check(curr_ad) and self._min_check(
                    curr_ad) and self._stop_check(
                                curr_ad):
            result = True
        else:
            result = False
        return result

    def _is_trade_repeating(self, con_id):
        for i in OpenTrades.objects.all():
            if con_id == i.trade_id:
                return True
        return False

    def _isfirst(self):
        result = {'isfirst': None, 'compensate': 0}

        if result['isfirst'] is None:
            for i, item in enumerate(self.all_ads['data']['ad_list']):
                if item['data']['ad_id'] == self.ad_id and i - result['compensate'] == 0:
                    ad_below_me = self.all_ads['data']['ad_list'][i+1]
                    if self._filter_check(ad_below_me):
                        result['isfirst'] = True
                        break
                    else:
                        for l, item in enumerate(self.all_ads['data']['ad_list'][i+1:]):
                            if not self._filter_check(item):
                                result['compensate'] += 1
                            break
                        result['isfirst'] = True
                        result['compensate'] += 1
                        break
                else:
                    if self._filter_check(item):
                        result['isfirst'] = False
                        result['enemy'] = i
                        break
                    else:
                        result['compensate'] += 1
        return result

    def _update_price(self, enemy):
        target_price = Decimal()
        int_price = int()
        str_price = str()

        if self.trade_direction == 'buy-bitcoins-online':
            target_price = Decimal(
                float(
                    self.all_ads['data']['ad_list'][enemy]['data']
                    ['temp_price']) - self.step)
            int_price = int(round(target_price))
            if self.price_round:
                while int_price % 100 > 0:
                    int_price -= 1
            if int_price < int(self.stop_price):
                int_price = int(self.stop_price)
            str_price = str(int_price) + '.00'
        elif self.trade_direction == 'sell-bitcoins-online':
            target_price = Decimal(
                float(
                    self.all_ads['data']['ad_list'][enemy]['data']
                    ['temp_price']) + self.step)
            int_price = int(round(target_price))
            if self.price_round:
                while int_price % 100 > 0:
                    int_price += 1
            if int_price > int(self.stop_price):
                int_price = int(self.stop_price)
            str_price = str(int_price) + '.00'

        if int_price == int(
            Decimal(
                float(
                    self.my_ad['data']['ad_list'][0]['data']
                    ['temp_price']))):
            pass
        else:
            response = self.auth.call(
                'POST', self.endpoints['post_upd_equat'],
                params={'price_equation': '%s' % (str_price)})

    def check_ads(self):
        if not self.my_ad:
            self._get_ads()

        isfirst = self._isfirst()
        if isfirst['isfirst']:
            self._update_price(1+isfirst['compensate'])
        else:
            self._update_price(isfirst['enemy'])

    def send_first_message(self):
        self._get_open_trades()
        for i in self.opened_trades['data']['contact_list']:
            contact_id = i['data']['contact_id']
            ad_id = i['data']['advertisement']['id']
            if not i['data']['disputed_at'] and not self._is_trade_repeating(contact_id) and ad_id == self.ad_id:
                self.auth.call(
                    'POST',
                    self.endpoints['post_message']+str(contact_id)+'/',
                    params={'msg': self.greetings_text})
                self._get_all_notifications()
                for i in self.all_notif['data']:
                    if i['contact_id'] == contact_id:
                        self.auth.call(
                            'POST',
                            self.endpoints['mark_notification']+str(i['id'])+'/')
                        break
                OpenTrades.objects.create(trade_id=contact_id,
                                          username=self.username,
                                          adbot=self)
        self._check_closed_deals()

    def _check_closed_deals(self):
        self._get_released_trades()
        open_trades_qs = OpenTrades.objects.all()

        for i in self.released_trades['data']['contact_list']:
            for l in open_trades_qs:
                if i['data']['contact_id'] == l.trade_id:
                    self.auth.call(
                            'POST',

ad_bot/views.py
import dateutil.parser
import pandas as pd
import numpy as np
from decimal import *
from django.shortcuts import render, reverse, redirect
from django.views import generic, View
from .models import AdBot, ReportData
from .tasks import adbot_runner, calculate_report
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages


class IndexView(LoginRequiredMixin, View):
    http_method_names = ['get', 'post']
    login_url = '/profiles/login/'

    def get(self, request, *args, **kwargs):
        context = {}
        context['adbot'] = AdBot.objects.filter(username=request.user.id).order_by('name')
        #b = AdBot.objects.get(ad_id=724665)
        #b.api_connector_init()
        #from remote_pdb import RemotePdb
        #RemotePdb('127.0.0.1', 4444).set_trace()
        #import pdb; pdb.set_trace()
        #b.check_ads()
        return render(request, 'ad_bot/index.html', context)


class SettingsView(LoginRequiredMixin, generic.ListView):
    model = AdBot
    template_name = 'ad_bot/settings.html'

class SwitchView(View):
    http_method = ['post']

    def post(self, request, *args, **kwargs):
        bot_id = int(request.POST.get('bot_id'))
        bot = AdBot.objects.get(id=bot_id)
        if bot.switch:
            bot.switch = False
        else:
            bot.switch = True
        bot.save()
        return redirect('ad_bot:index')

class ReportsView(LoginRequiredMixin, View):
    http_method = ['get', 'post']
    login_url = '/profiles/login/'

    def get(self, request, *args, **kwargs):
        context = {}
        context['adbot'] = AdBot.objects.all()
        context['method'] = 'get'
        return render(request, 'ad_bot/reports.html', context)

    def post(self, request, *args, **kwargs):
        context = {}
        headers = ['num',
                   'date',
                   'contact_id',
                   'agent',
                   'price',
                   'amount_rub',
                   'amount_btc',
                   'fee_btc',
                 ]
        bot_id = int(request.POST.get('adbot_chooser'))
        context['adbot'] = AdBot.objects.all()
        if request.POST.get('date_1') and request.POST.get('date_2'):
            date_1 = dateutil.parser.parse(request.POST.get('date_1'), ignoretz=True)
            date_2 = dateutil.parser.parse(request.POST.get('date_2'), ignoretz=True)
        else:
            messages.success(request, 'Выберите даты')
            return render(request, 'ad_bot/reports.html', context)
        context['method'] = 'post'
        messages.success(request, 'Отчет успешно сформирован')
        context['report_raw'] = ReportData.objects.filter(adbot=bot_id,
                                                          date__range=(date_1, date_2),
                                                        ).order_by('-date')
        calc_data = []
        counter = 0
        for i in context['report_raw']:
            counter += 1
            calc_data.append([counter,
                              i.date,
                              i.contact_id,
                              i.agent,
                              i.price,
                              i.amount_rub,
                              i.amount_btc,
                              i.fee_btc,
                            ])
        if calc_data:
            df = pd.DataFrame(np.array(calc_data),
                              index=range(len(calc_data)),
                              columns=headers)
            context['mean_price'] = round(df['price'].mean(), 2)
            context['sum_rub'] = df['amount_rub'].sum()
            context['sum_rub_qiwi'] = context['sum_rub'] - (context['sum_rub']*Decimal(0.018))
            context['sum_btc'] = df['amount_btc'].sum()
            context['fee_sum'] = df['fee_btc'].sum()
            context['sum_all_btc'] = context['fee_sum'] + context['sum_btc']
            context['number_trades'] = counter
            context['is_data'] = '2'
        else:
            context['is_data'] = '1'

        return render(request, 'ad_bot/reports.html', context)

class UpdateData(LoginRequiredMixin, View):
    http_method = ['get']
    login_url = '/profiles/login/'

    def get(self, request, *args, **kwargs):
        calculate_report.delay()
        messages.success(request, 'Задание на обновление успешно отправлено. Подождите некоторое время')
        return redirect('ad_bot:reports')

templates/ad_bot/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Состояние бота{% endblock %}


{% block nav_baractive_index %}active{% endblock %}


{% block content %}
    <div class="starter-template">
    
        <h1 class="bold"><b>Состояние бота</b></h1>

        {% if messages %}
        <div class="alert alert-success" role="alert">
            <ul class="messages ">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

    <div class="container">
      <div class="row">
        {% for adbot_qs in adbot %} 
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">		  
	      <h3>{{ adbot_qs.name }} <br />{{ adbot_qs.ad_id }}</h3>
	      {% if adbot_qs.switch %}
	      <form action="{% url 'ad_bot:switch' %}" method="post">
		{% csrf_token %}
		<input type='hidden' name='bot_id' value='{{ adbot_qs.id }}' />
		<button class="btn btn-success" type="submit"><b>Бот работает</b></button>
	      </form><br />
              {% else %}
	      <form action="{% url 'ad_bot:switch' %}" method="post">
		{% csrf_token %}
		<input type='hidden' name='bot_id' value='{{ adbot_qs.id }}' />
		<button class="btn btn-danger" type="submit"><b>Бот не работает</b></button>
	      </form><br />
	      {% endif %}
	      <p><b>{{ adbot_qs.get_payment_method_display }}</b> ||| <b>{{ adbot_qs.get_trade_direction_display }}</b></p>
	      <p><b>{{ adbot_qs.frequency }}</b> ||| <b>{{ adbot_qs.stop_price }}</b> ||| <b>{{ adbot_qs.step }}</b> <br /> <b>MAX: {{ adbot_qs.volume_max }}</b> ||| <b>MIN: {{ adbot_qs.volume_min }}</b></p>
	      {% comment %}
	      <p>Совершенные действия</p>
	      <div class="my-small">
	        {% for actionlog in actionlist %}
	      	  {% if adbot_qs.id == actionlog.bot_model.id %}  
		  {{ actionlog.timestamp|date:"Y-m-d, G:i:s" }} <br /> {{ actionlog.action }} <br />
		  {% endif %}
	        {% endfor %}
	      </div>
	      {% endcomment %}
	    </div>
	  </div>
	</div>
        {% endfor %}
      </div>
    </div>

{% endblock %}

templates/ad_bot/reports.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Отчеты{% endblock %}


{% block nav_baractive_reports %}active{% endblock %}


{% block content %}
  <div class="starter-template">
    
    <h1 class="bold"><b>Параметры отчета</b></h1>

    {% if messages %}
      <div class="alert alert-success" role="alert">
        <ul class="messages ">
	  {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}

    <div class="container">
      <form action="{% url 'ad_bot:reports' %}" method="post">
	{% csrf_token %}
	<select name = "adbot_chooser">
	  {% for i in adbot %}
	    <option value="{{i.id}}">{{ i.name }}</option>
	  {% endfor %}
	</select></br>
	</br><label for="date_1">Дата начала:</label>
	</br><p><input type="datetime-local" name="date_1"></p></br>
	<label for="date_2">Дата окончания:</label>
	<p><input type="datetime-local" name="date_2"></p></br>
	<button class="btn btn-success" type="submit"><b>Сформировать отчет</b></button>
      </form><br />
    </div>
  {% if method == "post" %}
	<p><b>Много раз не нажимать!</b></p>
	<a href={% url 'ad_bot:update' %}><button class="btn btn-danger"><b>Обновить данные вручную</b></button></a>
  {% endif %}

  {% if is_data == "2" %}
    <div class="container">
      <p><b>Средний курс:</b> {{ mean_price|floatformat:2 }}</p>
      <p><b>Cумма в рублях на Qiwi:</b> {{ sum_rub|floatformat:2 }}</p>
      <p><b>Сумма в рублях наличные (-1.8%):</b> {{ sum_rub_qiwi|floatformat:2 }}</p>
      <p><b>Cумма в битках:</b> {{ sum_all_btc|floatformat:8 }}</p>
      <p><b>Количество сделок:</b> {{ number_trades }}</p>

      <br /><div class="row">
        <div class="col border">Номер</div>
        <div class="col border">Дата</div>
        <div class="col border">ID</div>
        <div class="col border">Контрагент</div>
        <div class="col border">Курс</div>
        <div class="col border">Сумма в руб.</div>
        <div class="col border">Сумма в битках</div>
        <div class="col border">Комиссия в битках</div>
      </div>
      {% for i in report_raw %}
        <div class="row">
	  <div class="col border">{{ forloop.counter }}</div>
	  <div class="col border">{{ i.date }}</div>
          <div class="col border">{{ i.contact_id }}</div>
          <div class="col border">{{ i.agent }}</div>
          <div class="col border">{{ i.price|floatformat:2 }}</div>
          <div class="col border">{{ i.amount_rub|floatformat:0 }}</div>
          <div class="col border">{{ i.amount_btc|floatformat:8 }}</div>
          <div class="col border">{{ i.fee_btc|floatformat:8 }}</div>
        </div>
      {% endfor %}   
    </div>
  {% elif is_data == "1" %}
    <p><b>Нет информации по указанному периоду</b></p>
  {% endif %}
  </div>

{% endblock %}

templates/ad_bot/settings.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Bot settings{% endblock %}


{% block nav_baractive_settings %}active{% endblock %}


{% block content %}
    <div class="starter-template">
        <h1 class="bold reddish"><b>Настройки бота по объявлениям</b></h1>

        {% if messages %}
        <div class="alert alert-success" role="alert">
            <ul class="messages ">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <div class="container">
            <br /><div class="row">
                <div class="col border">id объявления</div>
                <div class="col border">Имя</div>
                <div class="col border">Работает</div>
                <div class="col border">API ключи</div>
                <div class="col border">Стоп цена</div>
                <div class="col border">Шаг</div>
                <div class="col border">Максимальный объем</div>
                <div class="col border">Минимальный объем</div>
                <div class="col border">Частота обновления</div>
            </div>
            {% for adbot in object_list %}
            <div class="row">
                <div class="col border">{{ adbot.ad_id }}</div>
                <div class="col border">{{ adbot.name }}</div>
		{% if adbot.switch %}
                <div class="col border">Да</div>
		{% else %}
		<div class="col border">Нет</div>
		{% endif %}
                <div class="col border">{{ adbot.api_keys }}</div>
                <div class="col border">{{ adbot.stop_price }}</div>
                <div class="col border">{{ adbot.step }}</div>
                <div class="col border">{{ adbot.volume_max }}</div>
                <div class="col border">{{ adbot.volume_min }}</div>
                <div class="col border">{{ adbot.frequency }}</div>
            </div>
	    {% endfor %}
{% endblock %}